name: CI

on:
  pull_request:
  push:
    branches: [main]

jobs:
  nix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DeterminateSystems/nix-installer-action@v17
      - uses: DeterminateSystems/magic-nix-cache-action@v13
      - name: Check flake
        run: nix flake check --show-trace
